[package]
name = "mini"
version = "0.1.0"
authors = ["Ed Felten <ed@felten.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.17.2"

[dependencies]
lalrpop-util = "0.17.2"
regex = "1"
num-bigint = "0.2.6"
num-traits = "0.2.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

